# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=32, null=True)),
                ('detailed_addrss', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('uname', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
