# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=64, verbose_name='小商品标题')),
                ('gtype', models.CharField(max_length=64, verbose_name='商品类别')),
                ('gprice', models.CharField(max_length=32, verbose_name='商品价格')),
                ('addtime', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('a_updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('isDelete', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goodsinfo',
                'ordering': ['-addtime'],
            },
        ),
        migrations.CreateModel(
            name='Typeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='商品分类')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('isDelete', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'typeinfo',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Typeinfo'),
        ),
    ]
