# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=64, verbose_name='小商品标题')),
                ('gtype', models.CharField(max_length=64, verbose_name='商品类别')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('gimg', models.ImageField(default='1', upload_to='uploads/%Y/%m/', verbose_name='图片')),
                ('ginfo', models.CharField(default='1', max_length=255, verbose_name='商品介绍')),
                ('gdetailed', tinymce.models.HTMLField(default='1')),
                ('gcommon', tinymce.models.HTMLField(default='1')),
                ('gsalesvolume', models.IntegerField(default='1', verbose_name='销量')),
                ('gevaluate', models.CharField(default='1', max_length=255, verbose_name='商品评论')),
                ('addtime', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('a_updatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('isDelete', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': '小商品信息',
                'verbose_name_plural': '小商品信息',
                'db_table': 'goodsinfo',
                'ordering': ['-addtime'],
            },
        ),
        migrations.CreateModel(
            name='Smallinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoname', models.CharField(max_length=32, verbose_name='水果小标题')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_delete', models.CharField(default='1', max_length=3)),
            ],
            options={
                'verbose_name': '水果小分类',
                'verbose_name_plural': '水果小分类',
                'db_table': 'small_info',
            },
        ),
        migrations.CreateModel(
            name='Typeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='商品分类')),
                ('judgefruit', models.CharField(default='1', max_length=32)),
                ('banner', models.ImageField(default='1', upload_to='banner/%Y/%m/', verbose_name='背景图')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('isDelete', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'typeinfo',
            },
        ),
        migrations.AddField(
            model_name='smallinfo',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Typeinfo'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Typeinfo'),
        ),
    ]
