# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joincars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsinfo', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('goodsnum', models.CharField(max_length=32, null=True, verbose_name='商品个数')),
                ('goodsprice', models.CharField(max_length=32, null=True, verbose_name='商品单价')),
                ('gtotalprice', models.CharField(default='', max_length=32, verbose_name='商品总价')),
                ('gimg', models.CharField(default='1', max_length=255, null=True, verbose_name='商品图片')),
                ('gcount', models.CharField(max_length=8, verbose_name='商品编码')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 'joincars',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=255, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDelete', models.CharField(default='1', max_length=32)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='joincars',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserInfo'),
        ),
    ]
